(#11628) Fix crash when Cancel button is selected
GTNewHorizons/ThaumicEnergistics pull request #26
Opened 2022-10-15 21:24 UTC by cwessel188

THIS CHANGE RELIES ON AE2 CHANGE at:
https://github.com/GTNewHorizons/Applied-Energistics-2-Unofficial/pull/194

Use Cancel Button from the base GUI instead of adding a new one. The button that was added was never the button that was sent into the ActionPerformed method.

Tested and verified in local server.

https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/issues/11628

2022-10-15 21:31 UTC, glowredman reviewed
Please edit the dependency declaration [here](https://github.com/GTNewHorizons/ThaumicEnergistics/blob/master/src/main/java/thaumicenergistics/common/ThaumicEnergistics.java#L36), such that FML complains to the user when they are trying to load the game with an AE2 version which doesn't have the feature you are relying on.

(This will only work after the AE2 PR is merged and tagged, so you know which version to paste there)

2022-10-16 01:18 UTC, cwessel188 commented
Will update dependency declaration once I have the new dependency

2022-10-29 07:40 UTC, minecraft7771 requested changes

2022-10-29 07:40 UTC, minecraft7771 commented on src/main/java/thaumicenergistics/common/ThaumicEnergistics.java
> +@Mod(modid = ThaumicEnergistics.MOD_ID, name = "Thaumic Energistics", version = ThaumicEnergistics.VERSION, dependencies = "required-after:ThE-core;required-after:appliedenergistics2@[rv3-beta-115,);
Isn't the required fix in 116?

2022-12-06 06:45 UTC, Dream-Master commented
@cwessel188 any news ?

2022-12-10 11:01 UTC, Dream-Master commented
yes it might be version 116 @cwessel188

2022-12-10 11:26 UTC, merged